apiVersion: v1
kind: ConfigMap
metadata:
  name: eshop-config
  namespace: eshop
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  IdentityUrlExternal: "http://identity-api.eshop.svc.cluster.local:8080"
---
apiVersion: v1
kind: Secret
metadata:
  name: eshop-secrets
  namespace: eshop
type: Opaque
stringData:
  # Base64 dönüşümünü OpenShift stringData sayesinde otomatik yapacak
  IdentityDbConnection: "Host=postgres;Database=identitydb;Username=postgres;Password=postgres"
  CatalogDbConnection: "Host=postgres;Database=catalogdb;Username=postgres;Password=postgres"
  OrderingDbConnection: "Host=postgres;Database=orderingdb;Username=postgres;Password=postgres"
  WebhooksDbConnection: "Host=postgres;Database=webhooksdb;Username=postgres;Password=postgres"
  EventBusConnection: "amqp://guest:guest@rabbitmq:5672"
  RedisConnection: "redis:6379"
