apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-api
  template:
    metadata:
      labels:
        app: identity-api
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: identity-api
          image: git.local:3000/admin/identity-api:latest
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ConnectionStrings__identitydb
              value: Host=postgres;Database=identitydb;Username=postgres;Password=postgres
            - name: WebAppClient
              value: http://eshop.local
            - name: IssuerUri
              value: http://identity.local
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "256Mi"
              cpu: "200m"
            requests:
              memory: "128Mi"
              cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: identity-api
  namespace: default
spec:
  selector:
    app: identity-api
  ports:
    - port: 8080
      targetPort: 8080
