apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-api
  namespace: eshop
  labels:
    app: identity-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-api
  template:
    metadata:
      labels:
        app: identity-api
    spec:
      containers:
        - name: identity-api
          image: foriinji/identity.api:v1
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:8080"
            - name: ConnectionStrings__identitydb
              valueFrom:
                secretKeyRef:
                  name: eshop-secrets
                  key: IdentityDbConnection
          envFrom:
            - configMapRef:
                name: eshop-config
---
apiVersion: v1
kind: Service
metadata:
  name: identity-api
  namespace: eshop
spec:
  selector:
    app: identity-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: identity-api
  namespace: eshop
spec:
  to:
    kind: Service
    name: identity-api
  port:
    targetPort: 8080
