[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/id_rsa
ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[k3s_master]
k3s-master ansible_host=192.168.2.85

[k3s_worker]
k8s-worker ansible_host=192.168.2.86

[jenkins]
jenkins.local ansible_host=192.168.2.89

[monitoring]
monitoring-srv ansible_host=192.168.2.87

[security]
security.local ansible_host=192.168.2.91

[git]
git.local ansible_host=192.168.2.90

[vault]
vault.local ansible_host=192.168.2.92

[k3s_cluster:children]
k3s_master
k3s_worker
