apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: eshop
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: foriinji/webapp:v1
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:8080"
            - name: ConnectionStrings__eventbus
              valueFrom:
                secretKeyRef:
                  name: eshop-secrets
                  key: EventBusConnection
          envFrom:
            - configMapRef:
                name: eshop-config
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
  namespace: eshop
spec:
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: webapp
  namespace: eshop
spec:
  to:
    kind: Service
    name: webapp
  port:
    targetPort: 8080
