apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-processor
  namespace: eshop
  labels:
    app: order-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-processor
  template:
    metadata:
      labels:
        app: order-processor
    spec:
      containers:
        - name: order-processor
          image: foriinji/order-processor:v1
          env:
            - name: ConnectionStrings__orderingdb
              valueFrom:
                secretKeyRef:
                  name: eshop-secrets
                  key: OrderingDbConnection
            - name: ConnectionStrings__eventbus
              valueFrom:
                secretKeyRef:
                  name: eshop-secrets
                  key: EventBusConnection
          envFrom:
            - configMapRef:
                name: eshop-config
