FROM jenkins/jenkins:lts-jdk17

USER root

# Docker CLI kurulumu (Host socket ile konuşabilmek için)
RUN apt-get update && apt-get install -y \
    ca-certificates \
    curl \
    gnupg \
    lsb-release && \
    mkdir -p /etc/apt/keyrings && \
    curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg && \
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null && \
    apt-get update && apt-get install -y docker-ce-cli && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

USER jenkins

# Kritik Eklentilerin (Plugins) Önden Yüklenmesi
RUN jenkins-plugin-cli --plugins \
    "git:latest" \
    "gitea:latest" \
    "workflow-aggregator:latest" \
    "docker-workflow:latest" \
    "docker-plugin:latest" \
    "kubernetes:latest" \
    "kubernetes-cli:latest" \
    "sonar:latest" \
    "timestamper:latest" \
    "ws-cleanup:latest" \
    "pipeline-utility-steps:latest" \
    "junit:latest" \
    "coverage:latest" \
    "blueocean:latest"
