apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-processor
  namespace: eshop
  labels:
    app: payment-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-processor
  template:
    metadata:
      labels:
        app: payment-processor
    spec:
      containers:
        - name: payment-processor
          image: foriinji/payment-processor:v1
          env:
            - name: ConnectionStrings__eventbus
              valueFrom:
                secretKeyRef:
                  name: eshop-secrets
                  key: EventBusConnection
          envFrom:
            - configMapRef:
                name: eshop-config
